services:
  - type: web
    name: document-summarizer-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: AZURE_STORAGE_CONNECTION_STRING
        sync: false
      - key: AZURE_BLOB_CONTAINER
        sync: false
      - key: AZURE_FORMRECOGNIZER_ENDPOINT
        sync: false
      - key: AZURE_FORMRECOGNIZER_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT
        sync: false
